### ISSUE TITLE
Search for stores by geocoding

### ISSUE THREAD

**Issue by schugnic** [Diconium-WirVsVirus/dds-wvv-backend#24]
Use geocoding function from any geocoding service to translate user inputs to actual geo_json results like shapes or points. 

Nominatimgeocoding service: 
- https://nominatim.org/release-docs/latest/api/Search/ ( uses open streept map data )
- https://github.com/osm-search/Nominatim

Try nominatim out: https://nominatim.openstreetmap.org/search.php?q=&polygon_geojson=1&viewbox=

PRO:
- open source
- can be self hosted
- free, no costs apart from hosting
- postalcode search
- city, discritct, street, based search

CON:
- self hosting might be required

Google Maps Places API: 
https://developers.google.com/maps/documentation/geocoding/start?hl=de

PRO: 
- no hosting required
- easy to use
- very good results
- 200 $ worth of request free per month ( corresponds to 40 000 geocoding requests ) 

CONS:
- 5 $ per 1000 requests when the free budget is exceeded.

The result from places api can then be matched with an internal search engine on our end, which provides geo queries. Like elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-queries.html.

Therefore all stores will have to be indexed in elasticsearch.

TODOs. 

- Setup Elasticsearch
- Connect the Spring Boot App with Elasticsearch
- Index stores from commercetools in the elasticsearch DB
- Connect the Spring Boot App with any geocoding service
- Define a new Search API in the Spring Boot App which uses Google Maps and the Elasticsearchengine

**Comment by schugnic** [comment]
On Slack @PapaBravo posted this constructive Solution 

I want to add that commercetools already allows for geo search (points only) on channels. So the feature "shops in my area" would be simple to implement

Channel has the attribute geoLocation: https://docs.commercetools.com/http-api-projects-channels#channeldraft
The Query Predicates Doc has an example https://docs.commercetools.com/http-api-query-predicates.html
API and other technical documentation of the commercetools platform - the leading PaaS solution for eCommerce.API and other technical documentation of the commercetools platform - the leading PaaS solution for eCommerce.
Channels HTTP API
Model the business with channels for supply and distribution(47 kB)
https://docs.commercetools.com/assets/img/opengraph-visual.png
API and other technical documentation of the commercetools platform - the leading PaaS solution for eCommerce.API and other technical documentation of the commercetools platform - the leading PaaS solution for eCommerce.
Query Predicates - commercetools platform
Learn about the commercetools platform - Query Predicates(47 kB)
https://docs.commercetools.com/assets/img/opengraph-visual.png

**Comment by schugnic** [comment]
Today in the daily we agreed, that we want to implement a basic radius search with google maps and commercetools.

The user puts in any free text as in gooogle maps like street, city, postalcode etc.
The geocoding service geocodes the free text to a geo json point.
We will use this geo json point to do a radius search in commercetools channels api.

**Comment by haugthom** [comment]
Please check:
https://simplemaps.com/data/de-cities

We can use this data for free an dont need to ask google for that.
