### ISSUE TITLE
BUG - Globe showing with no link

### ISSUE THREAD

**Issue by rodriflo** [Diconium-WirVsVirus/dds-wvv-backend#50]
When clicking on the planet of this case: 

http://www.smallbusinesshero.de/stores/85c8fd07-071e-4f4c-9c68-0e5e772702b7

Either the background of the site alone shows, or nothing happens. If there is no link, the globe shouldn't be showing.

**Comment by cnasenberg** [comment]
We had the same problem for all stores of Schwesterherz and Küchenliebe. I corrected the format of all their URLs. I also corrected the Küchenliebe URL in general, it was pointing to the Schwesterherz onlineshop.
