### ISSUE TITLE
Allow CORS whitelisting on subdomain

### ISSUE THREAD

**Issue by PapaBravo** [Diconium-WirVsVirus/dds-wvv-backend#64]
@connorlanigan suggested 

> Spring has a method called "checkOrigin" in one of its classes that can be used to handle a CORS preflight request with custom code: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#checkOrigin-java.lang.String-

**Comment by PapaBravo** [comment]
Decided we won't need it any more

**Comment by jonathan-wiens** [comment]
What were the reasons that we don't need it? If we move e.g. to Azure then we need it again. I'm creating a separate issue to make configuring CORS headers possible

**Comment by jonathan-wiens** [comment]
#81
