### ISSUE TITLE
New stores: misch misch coffee, WESEN, Limonadenbaum und SCHATZL - IMPORTANT

### ISSUE THREAD

**Issue by KonstiSchaetz** [Diconium-WirVsVirus/dds-wvv-backend#65]
Pls upload until 22/04/20 latest

- [x] ID: 20-04-03 | misch misch coffee https://www.smallbusinesshero.de/stores/d1db6639-c6ae-4942-9954-1fbbdd42d435 
- [x] ID: 20-04-05 | WESEN https://www.smallbusinesshero.de/stores/f31d8773-9d2e-4bba-8ec2-81eb018cae6e 
- [x] ID 20-04-06 | Limonadenbaum https://www.smallbusinesshero.de/stores/6079c10a-7108-4b7b-8faf-d4c5487a239b
- [x] ID 20-04-04 | SCHATZL https://www.smallbusinesshero.de/stores/3d6b1e66-565d-492f-996c-3b9d678402f2

**Comment by cnasenberg** [comment]
@KonstiSchaetz bitte schau mal durch, ob alles da ist. :)
