### ISSUE TITLE
New stores: Loveco, Saloon Boots

### ISSUE THREAD

**Issue by KonstiSchaetz** [Diconium-WirVsVirus/dds-wvv-backend#66]
- [x] ID 20-04-01 | La Danse (was done already) https://www.smallbusinesshero.de/stores/5d60d99c-5133-47b7-9123-aaf042535c1d 
- [x] ID 20-04-08 | Loveco https://www.smallbusinesshero.de/stores/18bf8a1d-bb2f-4e31-bcf4-3bfa64069d72
- [x] ID 20-08-09 | Saloon Boots 035d67b9-https://www.smallbusinesshero.de/stores/035d67b9-a80d-405f-9b80-4085c4c3d187

**Comment by cnasenberg** [comment]
Done! @KonstiSchaetz, please review and inform store owners, if everything's okay. :)

**Comment by cnasenberg** [comment]
Oh, for both LOVECO and Saloon Boots, the store owner image i.e. the inside of the store was so much nicer than the outside - so I just swapped them. Maybe we can swap them back, once we get the new design.
