### ISSUE TITLE
Add /stores endpoint for #3

### ISSUE THREAD

**Issue by cnasenberg** [Diconium-WirVsVirus/dds-wvv-backend#7]
## Acceptance Criteria 
- [x]  /stores endpoint is available in deployed backend. 
- [x] Returns mock data. 

## Excludes 
- Connection to commerce tools. 

##Info 
- API Documentation: https://docs.google.com/document/d/1v9D8XToGbJJ3emQhzN3zmIBLR67XFM6mi1h2_yaorO4/edit# 
- Related to: https://github.com/Diconium-WirVsVirus/dds-wvv-frontend/issues/3

**Comment by schugnic** [comment]
@cnasenberg  Pls verify the api https://dds-wvv-backend.herokuapp.com/swagger-ui.html#/Stores%20AP

**Comment by cnasenberg** [comment]
Nice! :D What about the structure of the store model... Can we make it match the structure of a 'channel', at least roundabout? https://docs.commercetools.com/http-api-projects-channels

**Comment by schugnic** [comment]
@cnasenberg I think we should only give Infromation we wil need and not bload the whole json with uneeded data like createdAt, updatedAt, etc. The frontend should not need those kind of data.
