### ISSUE TITLE
Publish/Unpublish is ignored

### ISSUE THREAD

**Issue by PapaBravo** [Diconium-WirVsVirus/dds-wvv-backend#77]
Unpublishing doesn't work

**Comment by mehmanis** [comment]
The issue was the result of `isChannelPublished` method from `StoresService` class. 
Previously we were checking if custom field `published` is exist or not. 
```
 Boolean published = customFields.getFieldAsBoolean("published");
 return published != null;
```
As custom field `published` can also be `false`, changing return statement to following solved issue.
```
return published != null && published;
```

**Comment by PapaBravo** [comment]
Good find. I will fix that tonight unless you get there first!

**Comment by cnasenberg** [comment]
Fixed, merged and deployed to production.
